# Generated by Django 5.0.6 on 2024-06-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('emp_id', models.UUIDField()),
                ('salary', models.IntegerField()),
                ('description', models.TextField()),
                ('joining_date', models.DateField(auto_now=True)),
                ('applied_for_resignation', models.BooleanField(default=False)),
            ],
        ),
    ]
